mysite/urls.py
from django.contrib import admin
from django.urls import include,path

urlpatterns = [
    path('', include('polls.urls')),
    path('polls/', include('polls.urls')),
    path('admin/', admin.site.urls),
]

polls/urls.py
from django.urls import path

from . import views

app_name = "polls"
urlpatterns = [
    # ex: /polls/
    path('', views.index, name='index'),
    # ex: /polls/5/
    path('<int:question_id>/', views.question_view, name='question_view'),
    # ex: /polls/5/results/
    path('<int:question_id>/results/', views.question_results, name='question_results'),
    # ex: /polls/5/vote/
    path('<int:question_id>/vote/', views.question_vote, name='question_vote'),
]

polls/models.py
import datetime

from django.db import models
from django.utils import timezone

class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')

    def __str__(self):
        return self.question_text

    def was_published_recently(self):
        now = timezone.now()
        return self.pub_date >= timezone.now() - datetime.timedelta(days=1) and self.pub_date <= now # Check if the question was posted less than a day ago

class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text

polls/views.py
from django.shortcuts import render,get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect, Http404
from django.template import loader
from django.urls import reverse
from .models import Choice,Question

# Create your views here.

def index(request):
    latest_question_list = Question.objects.order_by('-pub_date')
    template = loader.get_template('polls/index.html')
    context = {
        'latest_question_list': latest_question_list,
    }
    return HttpResponse(template.render(context, request))

def question_results(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    
    template = loader.get_template('polls/question_results.html')
    context = {
        'question': question,
        'question_id': question_id,
    }
    return HttpResponse(template.render(context, request))

def question_vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        # Redisplay the question voting form.
        return render(request, 'polls/question_details.html', {
            'question': question,
            'error_message': "You didn't select a choice.",
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        return HttpResponseRedirect(reverse('polls:question_results', args=(question.id,)))


def question_view(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    
    template = loader.get_template('polls/question_details.html')
    context = {
        'question': question,
    }
    return HttpResponse(template.render(context, request))

polls/templates/polls/index.html
{% if latest_question_list %}
    Currently available polls:
    <br>
    <ul>
    {% for question in latest_question_list %}
        <li><a href="/polls/{{ question.id }}/">{{ question.question_text }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No polls are available.</p>
{% endif %}

polls/templates/polls/question_details.html
Question:
<br><h1>{{ question }}</h1>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<br>Vote:
<form action="{% url 'polls:question_vote' question.id %}" method="post">
{% csrf_token %}
{% for choice in question.choice_set.all %}
    <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
    <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br>
{% endfor %}
<input type="submit" value="Vote">
</form>

<br><br>
View results <a href="/polls/{{ question.id }}/results/">here</a>

polls/templates/polls/question_results.html
Results for question with id {{question_id}}:
<br>Question:
<br>{{question}}
<br><br>Results:
<br><br>
{% for choice in question.choice_set.all %}
    {{ choice.choice_text }} <br>
    <label>Votes: {{ choice.votes }}</label> <br>
{% endfor %}